### ISSUE TITLE
Tab configuration not working?

### ISSUE THREAD

**Issue by fouvry** [yoshiki/yaml-mode#12]
With yaml-indent-offset set to 4, I get a tab in the second level of indentation, e.g.

```
entry:
    first:
        - 'second'
```

When I press <tab> to indent for "first", it works correctly.  When I press <tab> to indent for "- 'second'" the cursor jumps to the correctly place, but inserts a tab instead of 8 spaces.  Setting indent-tabs-mode to nil in the mode hook makes it work correctly. IMO, it should work out-of-the-box ;-)

Many thanks!

**Comment by wasamasa** [comment]
This should be fixed since 2010: https://github.com/yoshiki/yaml-mode/commit/1fa61ecf697b64f87ba2fb3c3a453238f9aa0e41

I'm therefore closing this as `indent-tabs-mode` is set to `nil` and therefore the given example works as expected for me.
