### ISSUE TITLE
Should derive from prog-mode when available.

### ISSUE THREAD

**Issue by ToBeReplaced** [yoshiki/yaml-mode#17]
This will make it inherit everything from prog-mode, including modifications made by distributions like https://github.com/bbatsov/prelude .

**Comment by Devagamster** [comment]
This isn't a markup though. Yaml is very similar to json, just more readable. Json-mode inherits from javascript mode which inherits from *wait for it* prog-mode.

**Comment by wasamasa** [comment]
By that argumentation YAML shouldn't be derived from prog-mode because it isn't a subset of a programming language...

**Comment by Devagamster** [comment]
I'm gonna backtrack. You're totally right. XML which is even closer of a cousin inherits from text-mode. I retract my previous statement.
