### ISSUE TITLE
Display current "location"

### ISSUE THREAD

**Issue by davidw** [yoshiki/yaml-mode#2]
Wishlist:

In deeply nested YAML files, sometimes I get a bit lost.  A way to make yaml-mode display which nested map I'm in would be wonderful!

**Comment by tnguyen-rh** [comment]
@davidw I see that `which-function-mode` shows only top-level map.  Maybe that can be extended to recognize/display sub-maps?

**Comment by wasamasa** [comment]
https://github.com/knu/yaml-imenu.el
