### ISSUE TITLE
Broken font-locking

### ISSUE THREAD

**Issue by bbatsov** [yoshiki/yaml-mode#20]
Single quotes in unquoted strings are not handled properly. Words followed by a colon are problematic as well.

![screen shot 2014-08-29 at 2 41 42 pm](https://cloud.githubusercontent.com/assets/103882/4089755/1bb22d8c-2f72-11e4-8330-743b84e625ae.png)

**Comment by tomjakubowski** [comment]
Single-quotes in block strings are problematic too:

<img width="572" alt="screen shot 2016-03-21 at 6 47 52 pm" src="https://cloud.githubusercontent.com/assets/667901/13939810/70bfa158-ef95-11e5-978e-9acad6f75a2e.png">

**Comment by qx** [comment]
+1

**Comment by ninrod** [comment]
another example:

<img width="340" alt="screen shot 2017-02-04 at 09 50 59" src="https://cloud.githubusercontent.com/assets/8352747/22618291/cc5fd6f6-eabf-11e6-9601-63e87217df69.png">

**Comment by stephenjbarr** [comment]
+1 Any progress on this?

**Comment by rslack** [comment]
One solution would be to just remove single and double quote from the yaml-mode-syntax-table. There seems very little value in trying to differentiate strings since YAML is mostly text values anyway. Thoughts?

**Comment by asmeurer** [comment]
I think it's helpful. YAML isn't mostly strings. One of the big problems with YAML is that it assumes something is a string unless it can be interpreted as something else. So `3` will be read as an integer, but `3d` will be read as a string. It can be a problem with things like `3` and `3.0`, which aren't distinguishable unless you put them in quotes, which isn't good if 3.0 is supposed to be something like a version number.  So generally for best practice, you should use quotes, especially for things like version numbers. Syntax highlighting, if it works properly, is a good way to guard against this problem.

**Comment by josteink** [comment]
>  So generally for best practice, you should use quotes, especially for things like version numbers.

Which is all good and fair. Except that in the real world some files are machine-generated by software, and the format used is outside our control.

> Syntax highlighting, if it works properly, is a good way to guard against this problem.

In former case, this opinionated approach makes `yaml-mode` useless to edit config files for such programs (such as [homeassistant](https://github.com/home-assistant/home-assistant)).
