### ISSUE TITLE
yaml comment highlight.

### ISSUE THREAD

**Issue by zw963** [yoshiki/yaml-mode#26]
I have those yaml
```
search_page_pages_count_css: div#pagin-btm span.page-skip em
```

I think `#pagin-btm span.page-skip em`  face look like a comment is strange.

Thanks.

**Comment by wasamasa** [comment]
I've read the spec today and it appears there's two situations where YAML considers something a comment:

- The comment is on its own line AKA `^#`
- The comment is inline and must be preceded by whitespace AKA `[ \t]#`

I'm not sure whether this can be encoded with syntax tables.  They currently specify comments as introduced by `#` which is not really correct.  It may satisfy the first case, but fails the second one.  Perhaps the two-character comment can be made to work with the prefix variant, if not I'll have to write my own font locking function taking care of comments.

**Comment by wasamasa** [comment]
Progress so far:

I have figured out how to make either comments preceded by a space or comments starting at the beginning of a line work.

Vanilla:

```elisp
(modify-syntax-entry ?# "<" yaml-mode-syntax-table)
(modify-syntax-entry ?\n ">" yaml-mode-syntax-table)
```

Leading space:

```elisp
(modify-syntax-entry ?\s ". 1" yaml-mode-syntax-table)
(modify-syntax-entry ?# ". 2" yaml-mode-syntax-table)
(modify-syntax-entry ?\n ">" yaml-mode-syntax-table)
```

Full line:

```elisp
(modify-syntax-entry ?\n "> 1" yaml-mode-syntax-table)
(modify-syntax-entry ?# ". 2" yaml-mode-syntax-table)
```

Combining these isn't straight-forward.  The following does *not* work:

```elisp
(modify-syntax-entry ?\s ". 1" yaml-mode-syntax-table)
(modify-syntax-entry ?# ". 2" yaml-mode-syntax-table)
(modify-syntax-entry ?\n "> 1" yaml-mode-syntax-table)
```

**Comment by wasamasa** [comment]
See http://emacs.stackexchange.com/a/20378/10 for more background.

**Comment by zw963** [comment]
Thanks.
