### ISSUE TITLE
Please, inherit `yaml-mode' from `prog-mode'

### ISSUE THREAD

**Issue by Alexander-Shukaev** [yoshiki/yaml-mode#27]
The title speaks for itself. What is the reason that you decided to inherit from `fundamental-mode`? Some people (including me) have things like

```
(add-hook 'text-mode-hook 'fci-mode)
(add-hook 'prog-mode-hook 'fci-mode)
```

which make life easier, and that's exactly one of those features what proper mode inheritance was intended for.

Thank you.

**Comment by squiter** [comment]
:+1:

**Comment by Alexander-Shukaev** [comment]
Why from `text-mode`?

**Comment by wasamasa** [comment]
For the same reason `rst-mode`, `xml-mode` and `tex-mode` do.  It's not a programming language.
