### ISSUE TITLE
highlighting

### ISSUE THREAD

**Issue by wilx** [yoshiki/yaml-mode#31]
The following snippet is weirdly highlighted. The second embedded (") character is considered a start of a string and is highlighted red until the next item in the collection:

~~~~
before_script:
  - |
      case "$CXX" in #(
      g++*) CXX=g++-5.2 #(
      ;;
      clang++*) CXX=clang++-3.7
      ;;
      esac
  - |
      case "$CC" in #(
      gcc*) CXX=gcc-5.2 #(
      ;;
      clang*) CXX=clang-3.7
      ;;
      esac
~~~~

**Comment by Wilfred** [comment]
I'm seeing the same thing. It occurs with single quotes too:

```
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH
```

**Comment by wasamasa** [comment]
Looks to me like a variant on literal blocks, but in a list.  Literal blocks are highlighted as strings (which takes care of embedded quotes), but the regex for deciding what a literal block is doesn't match this case.

**Comment by wasamasa** [comment]
Actually, according to `M-x regexp-builder`, the regex *does* match, so it's likely the buffer traversal in `yaml-font-lock-block-literals` that's going wrong.  As I cannot get edebug to trigger within it, it's time for printf-debugging or [font-lock-studio](https://github.com/Lindydancer/font-lock-studio).

**Comment by tnguyen-rh** [comment]
@wilx Seems like this problem is described in #20 -- maybe we can close this and concentrate on that one, instead?

**Comment by wilx** [comment]
@tnguyen-rh OK. I am closing this as duplicate of https://github.com/yoshiki/yaml-mode/issues/20.
