### ISSUE TITLE
Opening large yaml file is too slow

### ISSUE THREAD

**Issue by buzztaiki** [yoshiki/yaml-mode#37]
I have a large yaml file of amount of 3M bytes. I was kept waiting 8 seconds when opening this file.
I found that `font-lock-fontify-buffer` is called in `yaml-mode`. It is very slow because jit-lock is not activated at major mode called time.
I remove `font-lock-fontify-buffer` from `yaml-mode`, it became quite fast.
Why is `font-lock-fontify-buffer` called in `yaml-mode`?

**Comment by wasamasa** [comment]
I have no idea and as you've pointed out, this shouldn't be necessary for major modes.  So far I've only needed it when developing major and minor modes (to refresh font-lock keywords).

**Comment by buzztaiki** [comment]
Thank you!
