### ISSUE TITLE
Single quote (apostrophe) in string breaks syntax highlighting for rest of file

### ISSUE THREAD

**Issue by garrettr** [yoshiki/yaml-mode#39]
I've been encountering this a lot in Ansible playbooks, which use YAML. Here's a screenshot:

![screen shot 2016-04-12 at 3 55 32 pm](https://cloud.githubusercontent.com/assets/407302/14478131/b45d4472-00c7-11e6-9dab-95ed0f32d4a1.png)

**Comment by tnguyen-rh** [comment]
@garrettr Seems like this problem is described in #20 -- maybe we can close this and concentrate on that one, instead?
