### ISSUE TITLE
set safe-local-variable predicate for yaml-indent-offset

### ISSUE THREAD

**Issue by bhyde** [yoshiki/yaml-mode#41]
The addition of this :safe might be useful
```emacs-lisp
(defcustom yaml-indent-offset 2
  "*Amount of offset per level of indentation."
  :type 'integer
  :safe #'(lambda (x) (and (integerp x) (< -1 x 11)))
  :group 'yaml)
```

**Comment by wasamasa** [comment]
Not sure what problem this is solving.  Could you please elaborate?

**Comment by bhyde** [comment]
Imagine that your yaml file ends as follows:
```
# Local Variables:
#  mode: yaml
#  indent-tabs-mode: nil
#  yaml-indent-offset: 3
# End:
```
Mr. Emacs will nicely set those variables when it loads the file.   But he worries, so he only does it if he can be convinced it's safe.   One way to do that is for Mr. Awesome Developer to decorate his defcustom setup the :safe keyword as illustrated.   Mr Emac's actually looks to see if the variable has a safe-local-variable property.  So defcustom set's that from the value provided, which is a predicate to check that the given value is appropriate.

It is, yes, hard to see that from the doc; but defcustom points to the file local doc and there the safe-local-variable property is mentioned in passing.

**Comment by wasamasa** [comment]
Ah, I see.  I've just accepted that Emacs will always ask me about file-local variables, but haven't considered that one can deactivate that for a few select cases.  Thanks for your suggestion, I'll see what I can do.

**Comment by bhyde** [comment]
Thanks.  - Ben

PS. Your init.org is nice too.
