### ISSUE TITLE
Unknown keyword :safe

### ISSUE THREAD

**Issue by ocarlsen** [yoshiki/yaml-mode#50]
I get this error when I start up my emacs with yaml-mode.el.

Debugger entered--Lisp error: (error "Unknown keyword :safe")
  signal(error ("Unknown keyword :safe"))
  error("Unknown keyword %s" :safe)
  custom-handle-keyword(yaml-indent-offset :safe natnump custom-variable)
  custom-declare-variable(yaml-indent-offset 2 "*Amount of offset per level of indentation." :type integer :safe natnump :group yaml)
  (defcustom yaml-indent-offset 2 "*Amount of offset per level of indentation." :type (quote integer) :safe (quote natnump) :group (quote yaml))
  eval-buffer(#<buffer  *load*<2>> nil "/Users/ocarlsen/.emacs.d/lisp/yaml-mode.el" nil t)  ; Reading at buffer position 2673

**Comment by wasamasa** [comment]
What's your Emacs version?

**Comment by ocarlsen** [comment]
Oh yeah 22.1.1.

**Comment by ocarlsen** [comment]
It works with 24.1.  My bad.

**Comment by wasamasa** [comment]
Emacs 22.1 is from 2007 and thus a decade old.  Please configure your system to use something more up to date.
