### ISSUE TITLE
rubocop config render not correct.

### ISSUE THREAD

**Issue by zw963** [yoshiki/yaml-mode#51]
example is here: 

https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

from line 631, render color is broken.

Thanks

**Comment by bergey** [comment]
It looks as though `yaml-mode` doesn't correctly highlight block literals that contain quote characters.  `yaml-narrow-to-block-literal` works fine on these blocks.  I suspect some unintended interaction between `syntax-table` and `font-lock-keywords`.

**Comment by wasamasa** [comment]
I cannot reproduce this after merging #57.

**Comment by zw963** [comment]
Yes, it fixed now, thanks!
