### ISSUE TITLE
custom-theme-set-faces

### ISSUE THREAD

**Issue by arkhan** [yoshiki/yaml-mode#55]
Hello, 

I'm trying to change colors using custom-set-faces,
But I have not achieved it, what would be the way to do it, to get a different color combination than I have in the emacs theme ...?

Thanks

**Comment by wasamasa** [comment]
yaml-mode has only one customizable face for tabs, to customize its looks your theme has to change the `font-lock-*-face` family which is defined in `faces.el`.  Considering that nearly every theme in existence does this already, all you need to do is loading a theme you like.
