### ISSUE TITLE
Quote/apostrophe not handled correctly in all cases

### ISSUE THREAD

**Issue by Kaali** [yoshiki/yaml-mode#58]
PR #57 fixed apostrophe inside a word. But it broke quote handling when the previous letter is not a space. I originally didn't think of any cases where well formatted YAML quote was not prefixed with a space, but JSON style dictionaries and lists are one.

e.g.

> key: ['key2': value]

Either the apostrophe detection code should handle `{` and `[` the same way as the whitespace. Or it should detect the apostrophe case by checking if the previous character is any unicode letter.

**Comment by wasamasa** [comment]
Hm, perhaps it would be wiser then to check for word syntax instead of spaces and tabs.  After all, your PR added word syntax to the embedded quote.  Does that work for you?

**Comment by Kaali** [comment]
I'll try it out later today.

**Comment by Kaali** [comment]
PR #59 version works properly at least for the following cases:

```
- key: 'foo'
- key's: foo
- key: foo's
- key: ['foo': bar]
- key: {'foo': bar's}
- key: { 'foo': bar}
- key: [foo: 'bar']
- key:'foo'
- baz: bar
```
