### ISSUE TITLE
Open a 3000 lines big yml config file, performance is very bad.

### ISSUE THREAD

**Issue by zw963** [yoshiki/yaml-mode#71]
Emacs is lag, and stop to work, CPU usage is 100% ......

And move point is very lag, edit is never possible.

BTW: this is a yml file which have I18n information.

**Comment by wasamasa** [comment]
This kind of bug report is useless unless you provide the problematic file. It would be even better if you could use this package to find out what exactly is causing the performance issue: https://github.com/Lindydancer/font-lock-profiler

**Comment by zw963** [comment]
Thank you for you answer, i create git here: https://gist.github.com/983f51b90e8ec5da0ef40a3cd8a20d85

Please check.

**Comment by zw963** [comment]
BTW: after do some edit(e.g. change some char), the emacs process is keep no response ...

**Comment by zw963** [comment]
![image](https://user-images.githubusercontent.com/549126/60755471-ba832580-a022-11e9-9de9-7ce14f8def0d.png)

**Comment by wasamasa** [comment]
I've actually tried this now and get no lag at all. Editing works fine, too. Please make sure to update to the latest version of yaml-mode, run `emacs -Q`, then `M-x package-initialize` and browse the file. If that fixes slowness for you, it's something in your Emacs config.

**Comment by zw963** [comment]
i find out the reason cause this issue, some after_save hook cause this.

thank you!
