### ISSUE TITLE
yaml-nested-map-re may match multiple lines

### ISSUE THREAD

**Issue by XeCycle** [yoshiki/yaml-mode#79]
https://github.com/yoshiki/yaml-mode/commit/ac21293ee6d66bb04e0fc6ebc332ee038a5a3824 says we want to filter out comments, and changed `.` to `[^#]`.  However `.` is defined as "any single character except a newline", this change causes the match to run for many lines and breaks indentation when editing in the middle of a document.  Maybe this should be `[^#\n]`; or is there a way to tell [`looking-at`](https://github.com/yoshiki/yaml-mode/blob/master/yaml-mode.el#L355) to consider only one line?

**Comment by wasamasa** [comment]
Only `looking-back` supports a limit. Could you please create a test file that breaks as is and is fixed with your proposed regexp change?

**Comment by XeCycle** [comment]
Okay; I found no hints on automated tests in the code, but something like this is enough:

```
# indent on line "bar: baz" should be same as "foo: bar"
a:
  foo: bar
  bar: baz
b:
  1
```

Current master indents that line to 4 spaces.

**Comment by dsedivec** [comment]
I'm hitting this too.  In case you need another example, most any [Ansible playbook][] will do.  Here's a nearly minimal example ([raw gist link for downloading][gist]):

```yaml
- hosts: all
  tasks:
    - debug: msg=hi!
```

If you put point at the end of the first line and press enter, you get four spaces of indent, not the two you expected.

[Ansible playbook]: https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#about-playbooks
[gist]: https://gist.github.com/dsedivec/ef71eaa760c8da70f93facb39b0f0f98/raw/86bf08a3e429d9cb0bd3adf8fa644aa5b07110cd/sample.yaml

**Comment by wasamasa** [comment]
Sorry for the late response, I've adapted the first example and pushed a fix.
