### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by sten0** [yoshiki/yaml-mode#83]
Hi, I noticed that master at 831ef3a is 23 commits ahead of 0.0.14, and these seem like bugfixes that you'll want users to have access to.  At this time, in Debian, we're preparing for the "freeze" where new versions of software cannot be imported.  Would you please consider tagging a release before Christmas if you'd like Debian stable users to have access to newer than 0.0.14?

Thanks,
Nicholas

**Comment by wasamasa** [comment]
Thanks for pointing this out. I've pushed 0.0.15 now.

**Comment by sten0** [comment]
> Thanks for pointing this out. I've pushed 0.0.15 now.

You're welcome!  I've uploaded the updated package to Debian.

P.S. I can upload new versions until the beginning of February, and can
cherry pick targeted fixes until the beginning of March.
